# Generated by Django 2.2.15 on 2020-08-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
