# Generated by Django 2.2.15 on 2020-09-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0002_auto_20200830_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMgmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='')),
                ('homeImage', models.ImageField(upload_to='')),
                ('carouselImage1', models.ImageField(upload_to='')),
                ('carouselImage2', models.ImageField(upload_to='')),
                ('carouselImage3', models.ImageField(upload_to='')),
                ('homeBlurb', models.TextField(max_length=1000)),
                ('aboutMainImage', models.ImageField(upload_to='')),
                ('aboutImage1', models.ImageField(upload_to='')),
                ('aboutImage2', models.ImageField(upload_to='')),
                ('aboutImage3', models.ImageField(upload_to='')),
                ('lizWord', models.TextField(max_length=1000)),
            ],
        ),
    ]
