# Generated by Django 2.2.15 on 2020-09-15 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0003_adminmgmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmgmt',
            name='homeBlurb',
        ),
        migrations.RemoveField(
            model_name='adminmgmt',
            name='lizWord',
        ),
    ]
