# Generated by Django 2.2.15 on 2020-08-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0004_auto_20200828_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
